[workspace]
resolver = "2"
members = [
    "crates/farbus-protocol",
    "crates/farbus-core",
    "crates/farbus-server",
    "crates/farbus-client",
    "crates/farbus-bench",
    "crates/farbus-gui",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/happyaspic-byte/FarBus"
rust-version = "1.80"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
